# Generated by Django 4.2.21 on 2025-05-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
