# Generated by Django 4.2.21 on 2025-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_tag_remove_post_created_at_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imatge',
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
