# Generated by Django 4.2.21 on 2025-05-28 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_email_author_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='caption',
            new_name='tag',
        ),
    ]
